apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wilt
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 339712809429.dkr.ecr.ap-southeast-2.amazonaws.com/wilt-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: wilt-secrets
            - configMapRef:
                name: wilt-config

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wilt
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: backend


